version: '3.8'

services:
  web:
    build: .
    container_name: web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
